#!/bin/bash
CONTAINER_ALREADY_STARTED="CONTAINER_ALREADY_STARTED_PLACEHOLDER"
if [ ! -e $CONTAINER_ALREADY_STARTED ];
then
  touch $CONTAINER_ALREADY_STARTED
  echo "-- First container startup --"
	cp -r /app/output1/* /app/output/
	rm -rf /app/output1/ 
	cd /app/
	export FLASK_APP=app.py 
	flask run
else
	systemctl start apache2
	cd /app/ 
	export FLASK_APP=app.py 
	flask run
fi